roles:
  - name: hostname
    src: https://github.com/alysoid/ansible-role-hostname
  - name: locale
    src: https://github.com/alysoid/ansible-role-locale
  - name: timezone
    src: https://github.com/alysoid/ansible-role-timezone
  - name: network
    src: https://github.com/alysoid/ansible-role-network
  - name: wireless
    src: https://github.com/alysoid/ansible-role-wireless
  - name: resolve
    src: https://github.com/alysoid/ansible-role-resolve
  - name: timesync
    src: https://github.com/alysoid/ansible-role-timesync
  - name: journald
    src: https://github.com/alysoid/ansible-systemd-journald
  - name: swap
    src: https://github.com/alysoid/ansible-role-swap
  - name: log2ram
    src: https://github.com/alysoid/ansible-role-log2ram
  - name: mount
    src: https://github.com/alysoid/ansible-role-mount
  - name: nfs
    src: https://github.com/alysoid/ansible-nfs-server
