collections:
  - name: community.general
  - name: community.docker

roles:
  - name: boot-config
    src: https://github.com/infothrill/ansible-role-rpi_boot_config
    version: '4.1.0'
  - name: hostname
    src: https://github.com/alysoid/ansible-role-hostname
  - name: locale
    src: https://github.com/alysoid/ansible-role-locale
  - name: timezone
    src: https://github.com/alysoid/ansible-role-timezone
  - name: network
    src: https://github.com/alysoid/ansible-role-network
  - name: wireless
    src: https://github.com/alysoid/ansible-role-wireless
  - name: resolve
    src: https://github.com/alysoid/ansible-role-resolve
  - name: timesync
    src: https://github.com/alysoid/ansible-role-timesync
  - name: swap
    src: https://github.com/alysoid/ansible-role-swap
