[http.routers]
  [http.routers.gerbera]
    service = "gerbera"
    entrypoints = ["websecure"]
    rule = "Host(`gerbera.andreabrandi.com`)"
    middlewares = ["traefik-forward-auth@docker"]
  [http.routers.gerbera.tls]
    certResolver = "letsencrypt"


[http.services]
  [http.services.gerbera.loadBalancer]
    [[http.services.gerbera.loadBalancer.servers]]
      url = "http://192.168.0.1:49494"
