---
- name: "Self-Hosted: Samba configuration files"
  hosts: raspberrys
  become: yes
  remote_user: "{{ username }}"
  roles:
    - { role: samba, tags: [samba] }

- name: "Self-Hosted: Samba container"
  hosts: raspberrys
  become: yes
  remote_user: "{{ username }}"
  tasks:
    - name: "Docker Compose: Samba container"
      community.docker.docker_compose:
        project_name: samba-shares
        definition:
          services:
            #
            # Samba file server
            # https://github.com/mschirrmeister/docker-samba-server
            #
            samba:
              image: mschirrmeister/samba-server:latest
              container_name: samba
              restart: unless-stopped
              environment:
                USERNAME: "{{ username }}"
                PASSWORD: "{{ samba_password }}"
              volumes:
                - /etc/samba:/etc/samba
                - /mnt/storage:/mnt/storage
              ports:
                - 139:139/tcp
                - 445:445/tcp
        build: yes
        state: present
        stopped: no
        restarted: yes
