---
- name: "Self-Hosted: Update system and install custom packages"
  hosts: raspberrys
  become: yes
  remote_user: "{{ username }}"
  tasks:
    - name: Update system with 'pacman -Syu'
      community.general.pacman:
        update_cache: yes
        upgrade: yes
    - name: Install custom packages
      ansible.builtin.package:
        name: "{{ system_packages | default([]) }}"
        state: present

  roles:
    - { role: boot-config, tags: [boot-config] }
    - { role: hostname, tags: [hostname] }
    - { role: locale, tags: [locale] }
    - { role: timezone, tags: [timezone] }
    - { role: network, tags: [network] }
    - { role: wireless, tags: [wireless] }
    - { role: resolve, tags: [resolve] }
