---
- name: "Self-Hosted: Update system and install custom packages"
  hosts: raspberrys
  become: yes
  remote_user: "{{ username }}"
  tasks:
    - name: Update system with 'pacman -Syu'
      community.general.pacman:
        update_cache: yes
        upgrade: yes
    - name: Install system packages
      ansible.builtin.package:
        name: "{{ system_packages | default([]) }}"
        state: present
    - name: Configure system services
      ansible.builtin.systemd:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: "{{ item.enabled }}"
      loop: "{{ system_services | default([]) }}"

- name: "Self-Hosted: Deploy and configure system software and services"
  hosts: raspberrys
  become: yes
  remote_user: "{{ username }}"
  roles:
    - { role: boot-config, tags: [boot-config] }
    - { role: hostname, tags: [hostname] }
    - { role: locale, tags: [locale] }
    - { role: timezone, tags: [timezone] }
    - { role: network, tags: [network] }
    - { role: wireless, tags: [wireless] }
    - { role: resolve, tags: [resolve] }
    - { role: timesync, tags: [timesync] }
    - { role: swap, tags: [swap] }
    - { role: log2ram, tags: [log2ram] }
