timezone    = "Europe/Rome"
locale      = "it_IT.UTF-8"
keymap      = "us"
net_address = "192.168.0.1/24"
net_gateway = "192.168.0.254"
hostname    = "alpi"
username    = "alarm"
auth_sshkey = "build/id_rsa.pub"
