#
# Custom /boot/config.txt lines
# https://github.com/infothrill/ansible-role-rpi_boot_config
#
boot_config_lines:
  - 'gpu_mem=128'
  - 'disable_splash=1'

#
# System playbook
#
username: alarm

#
# Custom packages
#
system_packages:
  - git
  - zip
  - unzip
  - wget
  - htop

#
# Hostname
# https://github.com/alysoid/ansible-role-hostname
#
hostname: alpi
hostname_aliases: []

#
# Locale
# https://github.com/alysoid/ansible-role-locale
#
keymap: it
locale: it_IT.UTF-8
language: it_IT.UTF-8
