#
# Custom /boot/config.txt lines
# https://github.com/infothrill/ansible-role-rpi_boot_config
#
boot_config_lines:
  - 'gpu_mem=128'
  - 'disable_splash=1'

#
# System playbook
#
username: alarm

#
# Custom packages
#
system_packages:
  - git
  - zip
  - unzip
  - wget
  - htop
  - iwd

#
# Hostname
# https://github.com/alysoid/ansible-role-hostname
#
hostname: alpi
hostname_aliases: []

#
# Locale
# https://github.com/alysoid/ansible-role-locale
#
keymap: it
locale: it_IT.UTF-8
language: it_IT.UTF-8

#
# Timezone
# https://github.com/alysoid/ansible-role-timezone
#
timezone: Europe/Rome

#
# Systemd Swap (ZRam drives)
# https://github.com/alysoid/ansible-role-swap
#
systemd_swap_conf_d:
  zram_swap:
    - zram_enabled: 1
    - zram_size: $(( RAM_SIZE / 4 ))
    - zram_count: ${NCPU}
    - zram_streams: ${NCPU}
    - zram_alg: lz4
    - zram_prio: 32767
