#
# Custom /boot/config.txt lines
# https://github.com/infothrill/ansible-role-rpi_boot_config
#
boot_config_lines:
  - 'gpu_mem=128'
  - 'disable_splash=1'

#
# System playbook
#
username: alarm

#
# Custom packages
#
system_packages:
  - git
  - zip
  - unzip
  - wget
  - htop
  - iwd
  - systemd-swap
  - firewalld
  - docker
  - docker-compose
  - btrfs-progs

#
# System services
#
system_services:
  - name: firewalld.service
    state: started
    enabled: yes
  - name: docker.service
    state: started
    enabled: yes

#
# Hostname
# https://github.com/alysoid/ansible-role-hostname
#
hostname: alpi
hostname_aliases: []

#
# Locale
# https://github.com/alysoid/ansible-role-locale
#
keymap: us
locale: it_IT.UTF-8
language: it_IT.UTF-8

#
# Timezone
# https://github.com/alysoid/ansible-role-timezone
#
timezone: Europe/Rome

#
# Systemd journald
# https://github.com/alysoid/ansible-systemd-journald
#
systemd_journald:
  journald:
    - Journal:
      - Storage: persistent
      - SystemMaxUse: '100M'
      - SystemMaxFilesize: '100M'
      - SystemKeepFree: '50M'

#
# Systemd Swap (ZRam drives)
# https://github.com/alysoid/ansible-role-swap
#
systemd_swap_conf_d:
  zram_swap:
    - zram_enabled: 1
    - zram_size: $(( RAM_SIZE / 4 ))
    - zram_count: ${NCPU}
    - zram_streams: ${NCPU}
    - zram_alg: lz4
    - zram_prio: 32767

#
# Log2ram
# https://github.com/alysoid/ansible-role-log2ram
#
log2ram_size: '120M'
log2ram_send_mail: no
log2ram_path_disk: ['/var/log']
log2ram_zram_enabled: yes
log2ram_compression_algorithm: lz4

#
# Systemd Mount
# https://github.com/alysoid/ansible-role-mount
#
systemd_mount:
  - name: Storage
    options:
      Mount:
        What: /dev/sda
        Where: /mnt/storage
        Type: btrfs
        Options: defaults
      Install:
        WantedBy: multi-user.target
